### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by h4nwei** [rajat95/Deep-Deghosting-HDR#10]
Dear @rajat95 @KRamPrabhakar ,

Thanks for you excellent job. the homepage has broken down for a long time. So I am here to request for another valid link to access the dataset and pre-trained parameters, for example, google drive. Thanks in advance.

Best,
Hanwei

**Comment by rajat95** [comment]
We have updates the new links to the model in the readme. Sorry for the delay
