### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by zhengge** [rajat95/Deep-Deghosting-HDR#2]
Hi @rajat95 ,
How to download the Database(582 varying exposure images) ?
Thank you.

**Comment by rajat95** [comment]
Hi

Sorry for late reply. We recently ran out of space on our server and are working to clean it up and upload the dataset again. It may take a couple of more days to resolve. Sorry about that.

**Comment by KRamPrabhakar** [comment]
Hi,

The dataset is available at http://val.serc.iisc.ernet.in/ICCP19/ link.
