### ISSUE TITLE
dataset link seems down

### ISSUE THREAD

**Issue by Arwen-yuan** [rajat95/Deep-Deghosting-HDR#4]
Hi, I tried to download your dataset through the link: http://val.serc.iisc.ernet.in/ICCP19/, but it raise error "This request could not be forwarded to the origin server or to any parent caches".

**Comment by KRamPrabhakar** [comment]
Thanks for bringing it to our notice. Due to some network issues, the link was not operational yesterday. Now, it is fixed and working.
