### ISSUE TITLE
Question about the training dataset of Refinement Network.

### ISSUE THREAD

**Issue by shengbokang** [rajat95/Deep-Deghosting-HDR#5]
Could you briefly describe how to build the training dataset for the Refinement Network during the research? 
Thanks.

______________________________________________________________________________

I found that you had put the dataset on http://val.serc.iisc.ernet.in/ICCP19/files/ICCP19_dataset/tar_files/. Is this dataset for training both Refinement and Fusion Network?

**Comment by KRamPrabhakar** [comment]
Hi,

Thanks for your interest in our work. The original static input sequence for the UCSD dataset is provided by Wu et al. on their GitHub page ([Link](https://github.com/elliottwu/DeepHDR/blob/master/dataset/download_dataset.sh)). In this dataset, for every dynamic sequence, the corresponding static sequence is also provided. We have used those static images to train the refinement network.
