### ISSUE TITLE
Key DeepFuse/downsample0/bias not found in checkpoint

### ISSUE THREAD

**Issue by LinziYuann** [rajat95/Deep-Deghosting-HDR#6]
Hi, I have downloaded the pre-trained model and run your code with the command “python infer.py --source_dir ./data_samples/test_set --fusion_model tied --ref_label 2 --gpu 0”, but got the error:
 "Key DeepFuse/downsample0/bias not found in checkpoint
	 [[node save_2/RestoreV2 (defined at infer.py:153) ]]"

Is there anything wrong with the model?
Thanks!

**Comment by rajat95** [comment]
Default checkpoint in infer.py is corresponding to triple encoder architecture. Can you change argument for fusion_model tied to triple_encoder ('--fusion_model triple_encoder' in the command) and try again? or if you want to try the tied model add '`--fusion_ckpt ./checkpoints/pretrined_tied_fusion/model150.ckpt`' to the above command

**Comment by LinziYuann** [comment]
Thanks! I have tried the command "python infer.py --fusion_model triple_encoder --ref_label 2" and it works. 

However, when I ran the command "python infer.py --fusion_model tied --ref_label 2 --fusion_ckpt ./checkpoints/pretrained_tied_fusion/model150.ckpt",I got an error:
"Assign requires shapes of both tensors to match. lhs shape= [3,3,6,32] rhs shape= [3,3,3,32]
 [[node save_2/Assign_17 (defined at infer.py:153) ]]"

**Comment by rajat95** [comment]
Can you add the option --hdr_channels 0 as well in the above command

**Comment by LinziYuann** [comment]
Thanks! It works now.
