### ISSUE TITLE
When inputing a single image

### ISSUE THREAD

**Issue by cty907372362** [rajat95/Deep-Deghosting-HDR#7]
I appreciate your work very much. I would like to ask you about the reconstruction of a single image, because the model is suitable for any number of inputs, so can the network be extended to the reconstruction of a single image without considering optical flow correction?  Thank you.

**Comment by rajat95** [comment]
You can try single image by copying the same image and passing it to each of the encoders. But we didn't try that and can't say what the results would be and I don't personally think it would be able to fill in the missing details or correct noise as loss functions never encouraged it to do that.
