### ISSUE TITLE
Unable to download the model

### ISSUE THREAD

**Issue by zdyshine** [rajat95/Deep-Deghosting-HDR#9]
Thank you for your sharing. The model download link in Checkpoint cannot be opened. Could you please provide a new download link? Thank you!

**Comment by rajat95** [comment]
The server is down for maintenance, I will update you here once we get it back running again. Sorry for the inconvenience.

**Comment by zdyshine** [comment]
Thank you for your reply. Best wish!

**Comment by zdyshine** [comment]
Hi, I am still looking forward to accessing the server since we want to make a fair comparison with the proposed method.  I wonder if there is another way to get the data and code, such as email or google drive and so on. I really appreciate any help you can provide.

**Comment by rajat95** [comment]
We have updated the new links to the model in the README file. Sorry for the delay.
